### ISSUE TITLE
Setting timeout on ClientBuilder::connect

### ISSUE THREAD

**Issue by ParadoxSpiral** [websockets-rs/rust-websocket#151]
Currently you cannot seem to do this, so connecting to e.g. wss://1.1.1.1 takes ~2m30s.
I use ws urls from user input, so it would be nice to be able to specify a timeout for the inital connecting.

**Comment by illegalprime** [comment]
@ParadoxSpiral is this `async` or `sync`? I think you can access the raw stream for `sync`  and I believe there is a combinator for the `async` stuff, but it's good to add a convenience function.

**Comment by illegalprime** [comment]
oh I misread your issue, I see it now and I'll add it.

**Comment by ParadoxSpiral** [comment]
I do this now with a Timer with the async client for anyone who wants to do the same, but I still think that this would be a nice addition.

**Comment by dbrgn** [comment]
I would also like to see a configurable timeout without messing with timer futures :)

**Comment by WyseNynja** [comment]
@ParadoxSpiral can you share your code for using a timer on an async client?

**Comment by ParadoxSpiral** [comment]
@WyseNynja I use [this timeout combinator](https://docs.rs/tokio/0.1.19/tokio/prelude/trait.FutureExt.html#method.timeout) from tokio.

**Comment by ParadoxSpiral** [comment]
Since there are other async utilities to achieve this I don't think it is necessary to add this feature, closing for now.

**Comment by Lawliet-Chan** [comment]
> Since there are other async utilities to achieve this I don't think it is necessary to add this feature, closing for now.

I think you can make this `timeout` as a param in `sync` ClientBuilder, just like:
```
ClientBuilder::new(url, options{timeout: 500})
```
