### ISSUE TITLE
#[derive(Debug)] (or impl Debug) for websocket::server::InvalidConnection<tokio_core::net::TcpStream, bytes::bytes::BytesMut>

### ISSUE THREAD

**Issue by Kixunil** [websockets-rs/rust-websocket#153]
Currently one can not use `unwrap()` on the result in order to quickly prototype.

```
   = note: the method `unwrap` exists but the following trait bounds were not satisfied:
           `websocket::server::InvalidConnection<tokio_core::net::TcpStream, bytes::bytes::BytesMut> : std::fmt::Debug`
```

**Comment by illegalprime** [comment]
@Kixunil unfortunately this cannot have `Debug` in it because `TcpStream` does not implement `Debug`.
Would simply having a custom implementation that says `TcpStream -> "TcpStream"` be OK?

**Comment by Kixunil** [comment]
Sure. It may also skip TcpStream entirely or provide address. Having information about why something failed is what's needed.
