### ISSUE TITLE
Avoid server panic on UnsupportedWebsocketVersion

### ISSUE THREAD

**Issue by marcelbuesing** [websockets-rs/rust-websocket#156]
```
cargo run --example async-server
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/async-server`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedWebsocketVersion', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
wscat -p "8" -c "localhost:2794"
```

This is I guess not necessarily related to the WebsocketVersion but maybe more to how to handle errors in general which occur here:
```
server.incoming()
        // we don't wanna save the stream if it drops
.map_err(|InvalidConnection { error, .. }| error)
```

Is there any guidance on how to avoid that the server crashes when one client tries to establish a connection in such a way ? Basically close the client connection and continue to serve new clients.

**Comment by kpp** [comment]
Take a look at https://github.com/websockets-rs/rust-websocket/pull/224
