### ISSUE TITLE
Turn rust-websocket into an organization?

### ISSUE THREAD

**Issue by vi** [websockets-rs/rust-websocket#171]
`rust-websocket` development is prone to hiatuses, and [users are complaining](https://www.reddit.com/r/rust/comments/8bqi6f/whats_the_status_of_websockets/).

Maybe the repository should be just turned into an organization, with multiple contributes having granted access to  publish to crates.io?

**Comment by enzious** [comment]
I'd put some time in on this.

**Comment by cyderize** [comment]
I'd be happy for this to happen - I'll try to set that up after next week when I have more time.

Sorry I've been unable to work on this for so long, and thanks to everyone who has submitted issues and PRs, I'll try to get to them soon.

**Comment by vi** [comment]
Maybe at least add the [Rust Bus][1]?

    cargo owner --add rust-bus-owner

[1]:https://users.rust-lang.org/t/bus-factor-1-for-crates/17046

**Comment by illegalprime** [comment]
@vi I agree with all this, I feel very guilty leaving this project alone during the semester and I'd love more people to look at it. I can't change the repo (I don't think I have permission). I'll try to add you and the rust bus as owners, its been too long.

**Comment by illegalprime** [comment]
@cyderize I can set up an organization, can you hit the button to transfer:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

**Comment by cyderize** [comment]
I've now transferred ownership to the organisation.
We'll still have to update stuff in the readme and cargo.toml to reflect the new repo location.

**Comment by vi** [comment]
@illegalprime , @cyderize Am I supposed to publish new versions to crates.io?

For example, I want to publish current master(a4c52998fa9d84150827e1c0c318c8280ea05c42) as `0.20.3` becase I want it for Websocat.

**Comment by illegalprime** [comment]
@vi you should be able to push now, try it and lmk

**Comment by vi** [comment]
@illegalprime , How do I enable Travis in the moved repository?

Travis does not acknowledge my access to the repository; I tried to allow it, but it requires some approval from ord owners: "Access request pending".

**Comment by dbrgn** [comment]
Great to see some more activity here :slightly_smiling_face:

**Comment by illegalprime** [comment]
OK @vi should be running, here's the first build:
https://travis-ci.com/websockets-rs/rust-websocket/builds/80795841

**Comment by dbrgn** [comment]
@illegalprime congrats! :tada:
