### ISSUE TITLE
How to send and receive messages in parallel?

### ISSUE THREAD

**Issue by avkonst** [websockets-rs/rust-websocket#177]
I have connected to wss using secure connection. Split() is not available in this case. But I need to write to and read from websocket client in parallel without blocking write by read ops. How can I achieve this?

**Comment by avkonst** [comment]
Does it also work if it is secure channel?

**Comment by vi** [comment]
As I said, it should contains `split` unconditionally (both for `connect_secure` and `connect_insecure`).

Have you already tried, but failed to do it?

**Comment by avkonst** [comment]
I have tried secure sync. Split function was not available. Maybe something
has changed since then or it is different for async example. Thanks. I will
try.

**Comment by vi** [comment]
> Maybe something has changed since then

Unlikely.

> or it is different for async example

Likely.

**Comment by kpp** [comment]
@avkonst take a look at https://github.com/websockets-rs/rust-websocket/blob/master/examples/ssl-client.rs#L53

**Comment by kpp** [comment]
Would you please close this issue as resolved?

**Comment by vi** [comment]
@kpp, Do you maybe want to help maintain `rust-websocket` project in general?

Currently it is semi-abandoned.

**Comment by kpp** [comment]
Well, I might help to resolve some issues, but I am not going to maintain it forever =)
