### ISSUE TITLE
 Fails to build on systems with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Fanael** [websockets-rs/rust-websocket#189]
See sfackler/rust-openssl#994.

rust-websocket pulls in native-tls 0.1, which depends on an old version of openssl that doesn't build on systems with OpenSSL 1.1.1.

**Comment by enzious** [comment]
OpenSSL 1.1.* is a big api break IIRC

Some distros have it "masked"

**Comment by vi** [comment]
It would be good it rust-websocket also supported native (non-C) crypto like [rustls](https://github.com/ctz/rustls).

**Comment by hweom** [comment]
Looks like there is a pull request already?
websockets-rs/rust-websocket/pull/186
