### ISSUE TITLE
Imports doesn't work on edition=2018

### ISSUE THREAD

**Issue by kper** [websockets-rs/rust-websocket#202]
The `async-server` example cannot compile with editon 2018 because it has `async` in path.

Code:
`use websocket::async::Server;`

Error:
```
error: expected identifier, found reserved keyword `async`                                           
  --> src/main.rs:16:16                                                                              
   |                                                                                                 
16 | use websocket::async::Server;                                                                   
   |                ^^^^^ expected identifier, found reserved keyword    
```

**Comment by vi** [comment]
[`r#async`](https://github.com/rust-lang/rfcs/blob/master/text/2151-raw-identifiers.md)?

**Comment by kper** [comment]
Works thanks :)

**Comment by vpzomtrrfrt** [comment]
While the r# syntax does work, that doesn't really seem like a solution

**Comment by vi** [comment]
What do you suggest instead?

Migration to new hyper 0.12 may be a rather breaking change, so it may be a good point to rename `async` to something else.

**Comment by vi** [comment]
> While the r# syntax does work, that doesn't really seem like a solution

Depending on acceptance of usage of r#raw r#identifier syntax for things other than compatibility.

```rust
let fk = 0.5;
let fm = 0.1;
let r#fn = (fk + fm)/2.0;
let Fn = 1.0 / r#fn;
```
