### ISSUE TITLE
Implement From<String> for OwnedMessage

### ISSUE THREAD

**Issue by jean-airoldie** [websockets-rs/rust-websocket#203]
Hi,
Is there any reason why [OwnedMessage](https://docs.rs/websocket/0.22.0/websocket/message) does not implement `From<String>`? Since it is used as a `SinkItem` of the [async client](https://docs.rs/websocket/0.22.0/websocket/client/async/type.Client.html), I can't use the `Sink` produced by the async client in the following fashion:
```rust
pub fn foo<S: Sink>(sink: &mut S)
where
    <S as Sink>::SinkItem: From<String>,
    <S as Sink>::SinkError: Debug,
{
    let text = "ok".to_string();
    sink.start_send(text.into()).unwrap();
}
```
In the current configuration, I am forced to define my own intermediary type which implements `From<String>` and `Into<OwnedMessage>`.

Thanks!

**Comment by vi** [comment]
> Is there any reason why OwnedMessage does not implement From<String>?

Probably no. Pull request is welcome.

**Comment by vi** [comment]
Yes.
