### ISSUE TITLE
Can't import websocket::ascync due to it being a keyword

### ISSUE THREAD

**Issue by PierreLeidbring** [websockets-rs/rust-websocket#207]
In  a new project running stable 1.32.0 I am unable to import websocket::async due to async being a keyword.

**Comment by zeyla** [comment]
You can use a raw identifier: `websocket::r#async`. [Docs here](https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/raw-identifiers.html)

**Comment by PierreLeidbring** [comment]
@zeyla Thank you, totally forget this feature existed!

**Comment by Schwusch** [comment]
If this is the recommended approach, iI think it should be reflected in the examples.
Otherwise I think it would be more appropriate to rename the module.

**Comment by vi** [comment]
Updating examples is a good and non-intrusive idea.

**Comment by vi** [comment]
Note: similar issue: #202

**Comment by kpp** [comment]
Would you please close this issue as resolved?

**Comment by PierreLeidbring** [comment]
Yes
