### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by ignatenkobrain** [websockets-rs/rust-websocket#211]
Please include full license text as it is requirement of MIT.

Thanks in advance!

**Comment by vi** [comment]
I see some MIT license snippet in `README` and also `license` metadata field in `Cargo.toml`. I don't see any mention of Apache licence in the project.

**Comment by ignatenkobrain** [comment]
I'm sorry for confusing you. I wanted to write MIT. But since I was opening quite a few of such issues, I messed it up. I have corrected original request.
