### ISSUE TITLE
unix domain sockets

### ISSUE THREAD

**Issue by david415** [websockets-rs/rust-websocket#215]
Please add features and or documentation so I can use a unix domain socket with your rust crate instead of TCP. Thanks.

**Comment by vi** [comment]
`websocket` can connect and serve websockets over arbitrary underlying protocol. I use it this way in my project [websocat](https://github.com/vi/websocat/blob/master/doc.md#l-ws-unix).

You need to use [`async_connect_on`](https://docs.rs/websocket/0.22.3/websocket/client/builder/struct.ClientBuilder.html) for client and [`into_ws`](https://docs.rs/websocket/0.22.3/websocket/server/upgrade/async/trait.IntoWs.html#tymethod.into_ws) for server. Maybe there are non-async methods for this as well.

**Comment by david415** [comment]
cool thanks
