### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by WyseNynja** [websockets-rs/rust-websocket#217]
I am updating a project with some outdated dependencies and noticed that websockets could be updated from 0.21.1 to 0.22.3.

I don't see any changelog here though. Am I missing it, or do you just use the git commit messages? have there been any breaking changes?

**Comment by vi** [comment]
Main point for 0.22 is updated Tokio. 0.21 uses legacy tokio-core.

Some other public dependencies (but not hyper) are also updated. For other changes see the commits:

```
$ git log --oneline v0.21.1..v0.22.3
d1d9fbfc (tag: v0.22.3) Bump version to 0.22.3
f3e179d3 Allow https:// instead of wss:// in async_connect too.
bc140036 Apply rustfmt because of CI, as usual
147c707c Fix clippies for CI
5bfa2c1e Merge pull request #209 from timvisee/master
924aa072 (originpull/209/head) Use same compiler feature as connect constraints for new function
f3e3e1ec Also assume websockets over HTTPS are secure
ad7df37b (tag: v0.22.2) Bump version for ?Sized
895a11a6 Update version (note: commits got reordered)
94c1aa92 Merge pull request #205 from sgrif/patch-1
069432a6 (originpull/205/head) Implement `AsTcpStream` for `Box<dyn AsTcpStream>`
f0f130c1 Merge pull request #204 from jean-airoldie/from_string
25a77d79 (originpull/204/head) Travis installs clippy from git repo if rustup fails
9d6d0c65 Updated travis' rustup components
285a4690 Ran cargo fmt
4ddf17e4 Added From<String> & From<Vec<u8>> for OwnedMessage
e2ad4632 Update bitflags dependency
c9684b52 Update some easy dependencies
94f41bc8 (tag: v0.22.0) Update version in README
94e35cc1 Support rust 1.28.0
4c0a6a0c Bump version to 0.22.0.
fcd85c1c (originpull/199/head) Use tokio 0.1 (update fmt)
96342c15 Use tokio 0.1 (update fmt)
df9633a1 Use tokio 0.1 (fixed bug when received data was lost after codec update)
13f41074 Use tokio 0.1 (reformat code)
318b32a7 Use tokio 0.1 (clippy error fix)
9913a2b2 Use tokio 0.1 (tokio reform updates)
```

Long-term plan is to update `websocket` to depend on `hyper 0.12` (or not depend on hyper at all), but it's compilcated. I tried extracting the codec part from http-facing part into a separate crate, but that's not yet published on crates.io.

Do you use sync or async mode of `websocket`?

**Comment by vi** [comment]
> Have there been any breaking changes?

Unlikely. If it compiles, it should work.

**Comment by WyseNynja** [comment]
Thank you! The migration from tokio-core to tokio definitely looks like a blocker for a lot of projects.

I am using the async mode of websocket, so that is good.
