### ISSUE TITLE
Make function for reconnect

### ISSUE THREAD

**Issue by DuckerMan** [websockets-rs/rust-websocket#218]

**Comment by vi** [comment]
What shall it do? I suppose reconnecting is just creating another WebSocket and dropping the old one.

**Comment by DuckerMan** [comment]
I cant change websocket in struct which already in use.

**Comment by vi** [comment]
[`RefCell`](https://doc.rust-lang.org/std/cell/struct.RefCell.html)/[`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html)?

You can make your own wrapper, like a WebSocket, but with reconnect. Maybe such wrapper can be upstreamed into `websocket` crate itself.

**Comment by DuckerMan** [comment]
Thanks.
