### ISSUE TITLE
Can't get async server examples working?

### ISSUE THREAD

**Issue by sdegutis** [websockets-rs/rust-websocket#250]
I added this to my dependencies:

```toml
tokio = "*"
websocket = "*"
futures = "*"
```

And then copied [async-server](https://github.com/websockets-rs/rust-websocket/blob/master/examples/async-server.rs) into a new main.rs file and tried running it with `cargo run`, and it failed with weird tokio errors, like "failed to resolve: could not find `reactor` in `tokio`".

I tried the same thing with the autobahn async server example, similar errors.

What am I doing wrong?

**Comment by vi** [comment]
It's for `tokio 0.1`, not for corrent `async fn`-friendly `tokio 0.2`

**Comment by sdegutis** [comment]
Oh ok thanks.
