### ISSUE TITLE
Support for `wasm32-wasi`

### ISSUE THREAD

**Issue by 1c3t3a** [websockets-rs/rust-websocket#261]
This crate currently doesn't compile to the WebAssembly `wasm32-unknown-unknown` target. It yields the following compile error:

```
cargo build --target wasm32-unknown-unknown
   Compiling net2 v0.2.37
   Compiling block-padding v0.1.5
   Compiling unicase v1.4.2
   Compiling httparse v1.5.1
   Compiling base64 v0.9.3
error[E0432]: unresolved import `sys`
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/tcp.rs:18:5
   |
18 | use sys::c;
   |     ^^^ maybe a missing crate `sys`?
error[E0432]: unresolved import `sys`
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/socket.rs:20:5
   |
20 | use sys;
   |     ^^^ no `sys` in the root

error[E0432]: unresolved import `sys`
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/socket.rs:21:5
   |
21 | use sys::c;
   |     ^^^ maybe a missing crate `sys`?

error[E0432]: unresolved import `sys`
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/ext.rs:19:5
   |
19 | use sys;
   |     ^^^ no `sys` in the root

error[E0432]: unresolved import `sys`
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/ext.rs:20:5
   |
20 | use sys::c;
   |     ^^^ maybe a missing crate `sys`?

error[E0412]: cannot find type `c_int` in this scope
  --> /Users/basti/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.37/src/socket.rs:28:24
   |
28 |     pub fn new(family: c_int, ty: c_int) -> io::Result<Socket> {
   |                        ^^^^^ not found in this scope
   |
help: consider importing this type alias
   |
11 | use std::os::raw::c_int;
   |

and so on...
```

Support for this target would enable usage in Wasm applications that are either running in the browser with crates like `web-sys` or in any freestanding runtime like `wasmer`.

**Comment by vi** [comment]
1. Are you sure you have the toolchain set correctly? Do other typical libraries get compiled properly for `wasm32-unknown-unknown`?
2. How are you planning to have Websocket library do IO in `wasm32-unknown-unknown`?
3. Have you tried `wasm32-wasi` instead of `wasm32-unknown-unknown`? It has a part of libstd, so more things may try to work. WASI's imports may actually be missing from the library you are building unless you actually use WASI things.

**Comment by 1c3t3a** [comment]
1. Yes, that was an old error message which I misleadingly copied first. The one you see in the edit version is the one I am seeing right now.
2. As mentioned above crates like [`web-sys`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/) could help interacting with IO - if I am planning to run my code in a browser. But you're right, WASI sounds more reasonable. 
3. Yes, but it errors when trying to compile openssl-sys. I ran into a similar issue when trying to compile another crate with an openssl-sys dependency.

The error looks like this:

```
cargo build --target wasm32-wasi
   Compiling openssl-sys v0.9.66
   Compiling unicode-normalization v0.1.19
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
error: failed to run custom build command for `openssl-sys v0.9.66`

Caused by:
  process didn't exit successfully: `/Users/basti/Documents/Projekte/rust/rust-websocket/target/debug/build/openssl-sys-bcdde98c06d187a7/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=WASM32_WASI_OPENSSL_LIB_DIR
  WASM32_WASI_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=WASM32_WASI_OPENSSL_INCLUDE_DIR
  WASM32_WASI_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=WASM32_WASI_OPENSSL_DIR
  WASM32_WASI_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32-wasi
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32_wasi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_wasm32-wasi
  cargo:rerun-if-env-changed=PKG_CONFIG_wasm32_wasi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32-wasi
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32_wasi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\n                Install a sysroot for the target platform and configure it via\n                PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\n                cross-compiling wrapper for pkg-config and set it via\n                PKG_CONFIG environment variable."

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-apple-darwin
  $TARGET = wasm32-wasi
  openssl-sys = 0.9.66
```

**Comment by 1c3t3a** [comment]
I looked into this and it looks like the problem lies inside Tokio. But there is a plan to support wasm in the future and also a related tracking issue: [#1597](https://github.com/tokio-rs/tokio/issues/1597)

As expected, the sync version of this crate compiles:
`cargo build --no-default-features --features sync --target wasm32-wasi`

**Comment by vi** [comment]
Note that if Tokio gains wasm support, it would likely be Tokio v1 (or later).

`rust-websocket` library is still based on Tokio 0.1 (pre-async/await), so that new Tokio thing would probably not be benefitial for that.

This library is semi-abandoned. Have you tried other libraries like tungstenite instead?

**Comment by vi** [comment]
> web-sys

If you want to use client WebSockets from browser, you'll probably want to use browser implementation of websockets, not do the WebSocket negotiation manually from within WebAssembly.

Maybe you just need [web_sys::WebSocket](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html)?

**Comment by 1c3t3a** [comment]
> Note that if Tokio gains wasm support, it would likely be Tokio v1 (or later).
> 
> `rust-websocket` library is still based on Tokio 0.1 (pre-async/await), so that new Tokio thing would probably not be benefitial for that.
> 
> This library is semi-abandoned. Have you tried other libraries like tungstenite instead?

Yep that might be the best idea. I am researching this for a socket.io library I maintain, so there is no external pressure for WASM support right now. 



> > web-sys
> 
> If you want to use client WebSockets from browser, you'll probably want to use browser implementation of websockets, not do the WebSocket negotiation manually from within WebAssembly.
> 
> Maybe you just need [web_sys::WebSocket](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html)?

Yep, that would be the way to go.
