### ISSUE TITLE
Examples for dumper people ? 

### ISSUE THREAD

**Issue by erikpa1** [websockets-rs/rust-websocket#278]
Hi, I don't want to say I'm inexperienced rust user (more like occasional) but I have no idea how to use your examples and implement it to my code...

In python websockets looks like this:

```
        ws = websocket.WebSocketApp(wsAddress,
                                    on_open=self.on_open,
                                    on_message=self.on_message,
                                    on_error=self.on_error,
                                    on_close=self.on_close)
```

```
    def on_error(self, ws, error):
        print(error)

    def on_close(self, ws, close_status_code, close_msg):
        print("### closed ###")

    def on_open(self, ws):
        ws.send('{"headers":{"X-ApiKey":"1723"},"method":"subscribe", "resource":"/feeds/"}')
```

My idea is / was to create  simple service for collecting IoT collector for position trackers we use in my company.

Workflow of our tracking system is:

1. open websocket
2. send api-key, feed you want to listen on
3. receive stream from tracking system.

And that all I want to have as one thread inside of my actix-web app... 

Could be really nice to create some websocket example (ssl) which match the python ideology. Is it possible?

**Comment by vi** [comment]
I recommend you to use [Tungstenite](https://crates.io/crates/tungstenite) library instead of legacy `rust-websocket`.

Here is example of the code similar to above:

```
fn main() {
    let mut ws = match tungstenite::connect("wss://ws.vi-server.org/mirror") {
        Ok((ws, _)) => ws,
        Err(_) => {
            // on_error
            return;
        }
    };
    // on_open

    match ws.send(tungstenite::Message::Text(r#"{"headers":{"X-ApiKey":"1723"},"method":"subscribe", "resource":"/feeds/"}"#.to_owned())) {
        Ok(()) => (),
        Err(_) => {
            // on_error
        }
    }

    loop {
        match ws.read() {
            Ok(msg) => {
                // on_message
                dbg!(msg);
            }
            Err(_) => {
                // on_error
            }
        }
    }

    // on_close
}
```

You can add Tungstenite to your project with a command like `cargo add tungstenite --features=native-tls`.

**Comment by erikpa1** [comment]
@vi Thanks I will try
